// Generated by CIRCT firtool-1.75.0
module DCacheDataArray(	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7]
  input          clock,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7]
  input          io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [11:0]  io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input          io_req_bits_write,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [255:0] io_req_bits_wdata,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [3:0]   io_req_bits_wordMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [7:0]   io_req_bits_eccMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [3:0]   io_req_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [255:0] io_resp_0,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [255:0] io_resp_1,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [255:0] io_resp_2,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [255:0] io_resp_3	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
);

  wire         rockettile_dcache_data_arrays_3_rdata_data_3_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:39]
  wire         rockettile_dcache_data_arrays_3_rdata_MPORT_3_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  wire         rockettile_dcache_data_arrays_2_rdata_data_2_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:39]
  wire         rockettile_dcache_data_arrays_2_rdata_MPORT_2_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  wire         rockettile_dcache_data_arrays_1_rdata_data_1_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:39]
  wire         rockettile_dcache_data_arrays_1_rdata_MPORT_1_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  wire         rockettile_dcache_data_arrays_0_rdata_data_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:39]
  wire         rockettile_dcache_data_arrays_0_rdata_MPORT_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  wire [255:0] _rockettile_dcache_data_arrays_3_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [255:0] _rockettile_dcache_data_arrays_2_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [255:0] _rockettile_dcache_data_arrays_1_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [255:0] _rockettile_dcache_data_arrays_0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [31:0]  _GEN = {io_req_bits_eccMask[7] & io_req_bits_way_en[3], io_req_bits_eccMask[6] & io_req_bits_way_en[3], io_req_bits_eccMask[5] & io_req_bits_way_en[3], io_req_bits_eccMask[4] & io_req_bits_way_en[3], io_req_bits_eccMask[3] & io_req_bits_way_en[3], io_req_bits_eccMask[2] & io_req_bits_way_en[3], io_req_bits_eccMask[1] & io_req_bits_way_en[3], io_req_bits_eccMask[0] & io_req_bits_way_en[3], io_req_bits_eccMask[7] & io_req_bits_way_en[2], io_req_bits_eccMask[6] & io_req_bits_way_en[2], io_req_bits_eccMask[5] & io_req_bits_way_en[2], io_req_bits_eccMask[4] & io_req_bits_way_en[2], io_req_bits_eccMask[3] & io_req_bits_way_en[2], io_req_bits_eccMask[2] & io_req_bits_way_en[2], io_req_bits_eccMask[1] & io_req_bits_way_en[2], io_req_bits_eccMask[0] & io_req_bits_way_en[2], io_req_bits_eccMask[7] & io_req_bits_way_en[1], io_req_bits_eccMask[6] & io_req_bits_way_en[1], io_req_bits_eccMask[5] & io_req_bits_way_en[1], io_req_bits_eccMask[4] & io_req_bits_way_en[1], io_req_bits_eccMask[3] & io_req_bits_way_en[1], io_req_bits_eccMask[2] & io_req_bits_way_en[1], io_req_bits_eccMask[1] & io_req_bits_way_en[1], io_req_bits_eccMask[0] & io_req_bits_way_en[1], io_req_bits_eccMask[7] & io_req_bits_way_en[0], io_req_bits_eccMask[6] & io_req_bits_way_en[0], io_req_bits_eccMask[5] & io_req_bits_way_en[0], io_req_bits_eccMask[4] & io_req_bits_way_en[0], io_req_bits_eccMask[3] & io_req_bits_way_en[0], io_req_bits_eccMask[2] & io_req_bits_way_en[0], io_req_bits_eccMask[1] & io_req_bits_way_en[0], io_req_bits_eccMask[0] & io_req_bits_way_en[0]};	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:56:82, :57:{87,108}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire         rdata_valid = io_req_valid & io_req_bits_wordMask[0];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:{30,83}]
  assign rockettile_dcache_data_arrays_0_rdata_MPORT_en = rdata_valid & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :72:17]
  assign rockettile_dcache_data_arrays_0_rdata_data_en = rdata_valid & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :77:{39,42}]
  wire         rdata_valid_1 = io_req_valid & io_req_bits_wordMask[1];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:{30,83}]
  assign rockettile_dcache_data_arrays_1_rdata_MPORT_1_en = rdata_valid_1 & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :72:17]
  assign rockettile_dcache_data_arrays_1_rdata_data_1_en = rdata_valid_1 & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :77:{39,42}]
  wire         rdata_valid_2 = io_req_valid & io_req_bits_wordMask[2];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:{30,83}]
  assign rockettile_dcache_data_arrays_2_rdata_MPORT_2_en = rdata_valid_2 & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :72:17]
  assign rockettile_dcache_data_arrays_2_rdata_data_2_en = rdata_valid_2 & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :77:{39,42}]
  wire         rdata_valid_3 = io_req_valid & io_req_bits_wordMask[3];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:{30,83}]
  assign rockettile_dcache_data_arrays_3_rdata_MPORT_3_en = rdata_valid_3 & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :72:17]
  assign rockettile_dcache_data_arrays_3_rdata_data_3_en = rdata_valid_3 & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:71:30, :77:{39,42}]
  rockettile_dcache_data_arrays_0 rockettile_dcache_data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[11:5]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:59:31]
    .RW0_en    (rockettile_dcache_data_arrays_0_rdata_data_en | rockettile_dcache_data_arrays_0_rdata_MPORT_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17, :77:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({4{io_req_bits_wdata[63:0]}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_0_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  rockettile_dcache_data_arrays_1 rockettile_dcache_data_arrays_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[11:5]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:59:31]
    .RW0_en    (rockettile_dcache_data_arrays_1_rdata_data_1_en | rockettile_dcache_data_arrays_1_rdata_MPORT_1_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17, :77:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({4{io_req_bits_wdata[127:64]}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_1_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  rockettile_dcache_data_arrays_2 rockettile_dcache_data_arrays_2 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[11:5]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:59:31]
    .RW0_en    (rockettile_dcache_data_arrays_2_rdata_data_2_en | rockettile_dcache_data_arrays_2_rdata_MPORT_2_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17, :77:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({4{io_req_bits_wdata[191:128]}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_2_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  rockettile_dcache_data_arrays_3 rockettile_dcache_data_arrays_3 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[11:5]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:59:31]
    .RW0_en    (rockettile_dcache_data_arrays_3_rdata_data_3_en | rockettile_dcache_data_arrays_3_rdata_MPORT_3_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17, :77:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({4{io_req_bits_wdata[255:192]}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_3_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign io_resp_0 = {_rockettile_dcache_data_arrays_3_RW0_rdata[63:0], _rockettile_dcache_data_arrays_2_RW0_rdata[63:0], _rockettile_dcache_data_arrays_1_RW0_rdata[63:0], _rockettile_dcache_data_arrays_0_RW0_rdata[63:0]};	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
  assign io_resp_1 = {_rockettile_dcache_data_arrays_3_RW0_rdata[127:64], _rockettile_dcache_data_arrays_2_RW0_rdata[127:64], _rockettile_dcache_data_arrays_1_RW0_rdata[127:64], _rockettile_dcache_data_arrays_0_RW0_rdata[127:64]};	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
  assign io_resp_2 = {_rockettile_dcache_data_arrays_3_RW0_rdata[191:128], _rockettile_dcache_data_arrays_2_RW0_rdata[191:128], _rockettile_dcache_data_arrays_1_RW0_rdata[191:128], _rockettile_dcache_data_arrays_0_RW0_rdata[191:128]};	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
  assign io_resp_3 = {_rockettile_dcache_data_arrays_3_RW0_rdata[255:192], _rockettile_dcache_data_arrays_2_RW0_rdata[255:192], _rockettile_dcache_data_arrays_1_RW0_rdata[255:192], _rockettile_dcache_data_arrays_0_RW0_rdata[255:192]};	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
endmodule

