// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLWidthWidget8(	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  input          clock,	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  input          reset,	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  output         auto_anon_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]   auto_anon_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]   auto_anon_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]   auto_anon_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [4:0]   auto_anon_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0]  auto_anon_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]   auto_anon_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0]  auto_anon_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_anon_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]   auto_anon_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]   auto_anon_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]   auto_anon_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [4:0]   auto_anon_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [4:0]   auto_anon_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_anon_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0]  auto_anon_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_anon_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]   auto_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]   auto_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]   auto_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [4:0]   auto_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0]  auto_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0]  auto_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [255:0] auto_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_anon_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]   auto_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]   auto_anon_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]   auto_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [4:0]   auto_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [4:0]   auto_anon_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [255:0] auto_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_anon_out_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire             _repeated_repeater_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [2:0]       _repeated_repeater_io_deq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [1:0]       _repeated_repeater_io_deq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [3:0]       _repeated_repeater_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [4:0]       _repeated_repeater_io_deq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [4:0]       _repeated_repeater_io_deq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire             _repeated_repeater_io_deq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [255:0]     _repeated_repeater_io_deq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire             _repeated_repeater_io_deq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [19:0]      _limit_T = 20'h1F << auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  reg  [1:0]       count;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27]
  wire             last = count == ~(_limit_T[4:3]) | auto_anon_in_a_bits_opcode[2];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27, :42:{26,36}, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  wire             enable_0 = (count & ~(_limit_T[4:3])) == 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27, :43:{63,72}, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  wire             enable_1 = ({count[1], ~(count[0])} & ~(_limit_T[4:3])) == 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27, :43:{56,63,72}, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  wire             enable_2 = ((count ^ 2'h2) & ~(_limit_T[4:3])) == 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27, :43:{56,63,72}, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  reg              corrupt_reg;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:45:32]
  wire             corrupt_out = auto_anon_in_a_bits_corrupt | corrupt_reg;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:45:32, :47:36]
  wire             anonIn_a_ready = auto_anon_out_a_ready | ~last;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:42:36, :76:{29,32}]
  reg              anonOut_a_bits_data_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:62:41]
  wire             anonOut_a_bits_data_masked_enable_0 = enable_0 | ~anonOut_a_bits_data_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:43:72, :62:41, :63:{42,45}]
  wire             anonOut_a_bits_data_masked_enable_1 = enable_1 | ~anonOut_a_bits_data_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:43:72, :62:41, :63:{42,45}]
  wire             anonOut_a_bits_data_masked_enable_2 = enable_2 | ~anonOut_a_bits_data_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:43:72, :62:41, :63:{42,45}]
  reg  [63:0]      anonOut_a_bits_data_rdata_0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
  reg  [63:0]      anonOut_a_bits_data_rdata_1;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
  reg  [63:0]      anonOut_a_bits_data_rdata_2;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
  wire             anonOut_a_bits_mask_sub_sub_sub_sub_sub_0_1 = auto_anon_in_a_bits_size > 4'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire             anonOut_a_bits_mask_sub_sub_sub_sub_size = auto_anon_in_a_bits_size[2:0] == 3'h4;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49]
  wire             anonOut_a_bits_mask_sub_sub_sub_sub_0_1 = anonOut_a_bits_mask_sub_sub_sub_sub_sub_0_1 | anonOut_a_bits_mask_sub_sub_sub_sub_size & ~(auto_anon_in_a_bits_address[4]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_sub_sub_1_1 = anonOut_a_bits_mask_sub_sub_sub_sub_sub_0_1 | anonOut_a_bits_mask_sub_sub_sub_sub_size & auto_anon_in_a_bits_address[4];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_sub_size = auto_anon_in_a_bits_size[2:0] == 3'h3;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49]
  wire             anonOut_a_bits_mask_sub_sub_sub_0_2 = ~(auto_anon_in_a_bits_address[4]) & ~(auto_anon_in_a_bits_address[3]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_sub_0_1 = anonOut_a_bits_mask_sub_sub_sub_sub_0_1 | anonOut_a_bits_mask_sub_sub_sub_size & anonOut_a_bits_mask_sub_sub_sub_0_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_sub_1_2 = ~(auto_anon_in_a_bits_address[4]) & auto_anon_in_a_bits_address[3];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_sub_1_1 = anonOut_a_bits_mask_sub_sub_sub_sub_0_1 | anonOut_a_bits_mask_sub_sub_sub_size & anonOut_a_bits_mask_sub_sub_sub_1_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_sub_2_2 = auto_anon_in_a_bits_address[4] & ~(auto_anon_in_a_bits_address[3]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_sub_2_1 = anonOut_a_bits_mask_sub_sub_sub_sub_1_1 | anonOut_a_bits_mask_sub_sub_sub_size & anonOut_a_bits_mask_sub_sub_sub_2_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_sub_3_2 = auto_anon_in_a_bits_address[4] & auto_anon_in_a_bits_address[3];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_sub_3_1 = anonOut_a_bits_mask_sub_sub_sub_sub_1_1 | anonOut_a_bits_mask_sub_sub_sub_size & anonOut_a_bits_mask_sub_sub_sub_3_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_size = auto_anon_in_a_bits_size[2:0] == 3'h2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49]
  wire             anonOut_a_bits_mask_sub_sub_0_2 = anonOut_a_bits_mask_sub_sub_sub_0_2 & ~(auto_anon_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_0_1 = anonOut_a_bits_mask_sub_sub_sub_0_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_0_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_1_2 = anonOut_a_bits_mask_sub_sub_sub_0_2 & auto_anon_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_1_1 = anonOut_a_bits_mask_sub_sub_sub_0_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_1_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_2_2 = anonOut_a_bits_mask_sub_sub_sub_1_2 & ~(auto_anon_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_2_1 = anonOut_a_bits_mask_sub_sub_sub_1_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_2_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_3_2 = anonOut_a_bits_mask_sub_sub_sub_1_2 & auto_anon_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_3_1 = anonOut_a_bits_mask_sub_sub_sub_1_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_3_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_4_2 = anonOut_a_bits_mask_sub_sub_sub_2_2 & ~(auto_anon_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_4_1 = anonOut_a_bits_mask_sub_sub_sub_2_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_4_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_5_2 = anonOut_a_bits_mask_sub_sub_sub_2_2 & auto_anon_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_5_1 = anonOut_a_bits_mask_sub_sub_sub_2_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_5_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_6_2 = anonOut_a_bits_mask_sub_sub_sub_3_2 & ~(auto_anon_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_6_1 = anonOut_a_bits_mask_sub_sub_sub_3_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_6_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_sub_7_2 = anonOut_a_bits_mask_sub_sub_sub_3_2 & auto_anon_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_sub_7_1 = anonOut_a_bits_mask_sub_sub_sub_3_1 | anonOut_a_bits_mask_sub_sub_size & anonOut_a_bits_mask_sub_sub_7_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_size = auto_anon_in_a_bits_size[2:0] == 3'h1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49]
  wire             anonOut_a_bits_mask_sub_0_2 = anonOut_a_bits_mask_sub_sub_0_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_0_1 = anonOut_a_bits_mask_sub_sub_0_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_0_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_1_2 = anonOut_a_bits_mask_sub_sub_0_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_1_1 = anonOut_a_bits_mask_sub_sub_0_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_1_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_2_2 = anonOut_a_bits_mask_sub_sub_1_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_2_1 = anonOut_a_bits_mask_sub_sub_1_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_2_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_3_2 = anonOut_a_bits_mask_sub_sub_1_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_3_1 = anonOut_a_bits_mask_sub_sub_1_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_3_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_4_2 = anonOut_a_bits_mask_sub_sub_2_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_4_1 = anonOut_a_bits_mask_sub_sub_2_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_4_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_5_2 = anonOut_a_bits_mask_sub_sub_2_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_5_1 = anonOut_a_bits_mask_sub_sub_2_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_5_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_6_2 = anonOut_a_bits_mask_sub_sub_3_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_6_1 = anonOut_a_bits_mask_sub_sub_3_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_6_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_7_2 = anonOut_a_bits_mask_sub_sub_3_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_7_1 = anonOut_a_bits_mask_sub_sub_3_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_7_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_8_2 = anonOut_a_bits_mask_sub_sub_4_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_8_1 = anonOut_a_bits_mask_sub_sub_4_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_8_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_9_2 = anonOut_a_bits_mask_sub_sub_4_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_9_1 = anonOut_a_bits_mask_sub_sub_4_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_9_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_10_2 = anonOut_a_bits_mask_sub_sub_5_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_10_1 = anonOut_a_bits_mask_sub_sub_5_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_10_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_11_2 = anonOut_a_bits_mask_sub_sub_5_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_11_1 = anonOut_a_bits_mask_sub_sub_5_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_11_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_12_2 = anonOut_a_bits_mask_sub_sub_6_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_12_1 = anonOut_a_bits_mask_sub_sub_6_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_12_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_13_2 = anonOut_a_bits_mask_sub_sub_6_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_13_1 = anonOut_a_bits_mask_sub_sub_6_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_13_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_14_2 = anonOut_a_bits_mask_sub_sub_7_2 & ~(auto_anon_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire             anonOut_a_bits_mask_sub_14_1 = anonOut_a_bits_mask_sub_sub_7_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_14_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire             anonOut_a_bits_mask_sub_15_2 = anonOut_a_bits_mask_sub_sub_7_2 & auto_anon_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire             anonOut_a_bits_mask_sub_15_1 = anonOut_a_bits_mask_sub_sub_7_1 | anonOut_a_bits_mask_sub_size & anonOut_a_bits_mask_sub_15_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  reg              anonOut_a_bits_mask_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:62:41]
  wire             anonOut_a_bits_mask_masked_enable_0 = enable_0 | ~anonOut_a_bits_mask_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:43:72, :62:41, :63:{42,45}]
  wire             anonOut_a_bits_mask_masked_enable_1 = enable_1 | ~anonOut_a_bits_mask_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:43:72, :62:41, :63:{42,45}]
  wire             anonOut_a_bits_mask_masked_enable_2 = enable_2 | ~anonOut_a_bits_mask_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:43:72, :62:41, :63:{42,45}]
  reg  [7:0]       anonOut_a_bits_mask_rdata_0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
  reg  [7:0]       anonOut_a_bits_mask_rdata_1;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
  reg  [7:0]       anonOut_a_bits_mask_rdata_2;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
  wire [19:0]      _repeat_limit_T = 20'h1F << _repeated_repeater_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26, generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  reg  [1:0]       repeat_count;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:105:26]
  wire             repeat_first = repeat_count == 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:105:26, :106:25]
  wire             repeat_last = repeat_count == ~(_repeat_limit_T[4:3]) | ~(_repeated_repeater_io_deq_bits_opcode[0]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:105:26, :107:{25,35,38}, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  reg  [1:0]       repeat_sel_sel_sources_0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_1;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_2;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_3;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_4;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_5;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_6;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_7;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_8;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_9;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_10;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_11;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_12;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_13;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_14;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_15;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_sel_sources_16;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27]
  reg  [1:0]       repeat_sel_hold_r;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:121:47]
  wire [31:0][1:0] _GEN = {{repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_0}, {repeat_sel_sel_sources_16}, {repeat_sel_sel_sources_15}, {repeat_sel_sel_sources_14}, {repeat_sel_sel_sources_13}, {repeat_sel_sel_sources_12}, {repeat_sel_sel_sources_11}, {repeat_sel_sel_sources_10}, {repeat_sel_sel_sources_9}, {repeat_sel_sel_sources_8}, {repeat_sel_sel_sources_7}, {repeat_sel_sel_sources_6}, {repeat_sel_sel_sources_5}, {repeat_sel_sel_sources_4}, {repeat_sel_sel_sources_3}, {repeat_sel_sel_sources_2}, {repeat_sel_sel_sources_1}, {repeat_sel_sel_sources_0}};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:121:47, :187:27]
  wire [1:0]       _GEN_0 = _GEN[_repeated_repeater_io_deq_bits_source];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:121:47, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire [3:0][63:0] _GEN_1 = {{_repeated_repeater_io_deq_bits_data[255:192]}, {_repeated_repeater_io_deq_bits_data[191:128]}, {_repeated_repeater_io_deq_bits_data[127:64]}, {auto_anon_out_d_bits_data[63:0]}};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:128:55, :137:30, :165:31, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  wire             _repeat_sel_sel_T = anonIn_a_ready & auto_anon_in_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:76:29, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _anonOut_a_bits_data_T_2 = _repeat_sel_sel_T & ~last;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:42:36, :69:23, :76:32, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _anonOut_a_bits_mask_T_3 = _repeat_sel_sel_T & ~last;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:42:36, :69:23, :76:32, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
      count <= 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27]
      corrupt_reg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:45:32]
      anonOut_a_bits_data_rdata_written_once <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:62:41]
      anonOut_a_bits_mask_rdata_written_once <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:62:41]
      repeat_count <= 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:105:26]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
      if (_repeat_sel_sel_T) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        count <= last ? 2'h0 : count + 2'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:40:27, :42:36, :50:{15,24}, :52:21, :53:17]
        corrupt_reg <= ~last & corrupt_out;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:42:36, :45:32, :47:36, :51:21, :52:21, :54:23]
      end
      anonOut_a_bits_data_rdata_written_once <= _anonOut_a_bits_data_T_2 | anonOut_a_bits_data_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:62:41, :69:{23,33}, :70:30]
      anonOut_a_bits_mask_rdata_written_once <= _anonOut_a_bits_mask_T_3 | anonOut_a_bits_mask_rdata_written_once;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:62:41, :69:{23,33}, :70:30]
      if (auto_anon_in_d_ready & _repeated_repeater_io_deq_valid)	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        repeat_count <= repeat_last ? 2'h0 : repeat_count + 2'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:105:26, :107:35, :110:{15,24}, :111:{21,29}]
    end
    if (_anonOut_a_bits_data_T_2 & anonOut_a_bits_data_masked_enable_0)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:63:42, :66:24, :68:88, :69:{23,33}, :71:56]
      anonOut_a_bits_data_rdata_0 <= auto_anon_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
    if (_anonOut_a_bits_data_T_2 & anonOut_a_bits_data_masked_enable_1)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:63:42, :66:24, :68:88, :69:{23,33}, :71:56]
      anonOut_a_bits_data_rdata_1 <= auto_anon_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
    if (_anonOut_a_bits_data_T_2 & anonOut_a_bits_data_masked_enable_2)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:63:42, :66:24, :68:88, :69:{23,33}, :71:56]
      anonOut_a_bits_data_rdata_2 <= auto_anon_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
    if (_anonOut_a_bits_mask_T_3 & anonOut_a_bits_mask_masked_enable_0)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:63:42, :66:24, :68:88, :69:{23,33}, :71:56]
      anonOut_a_bits_mask_rdata_0 <= auto_anon_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
    if (_anonOut_a_bits_mask_T_3 & anonOut_a_bits_mask_masked_enable_1)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:63:42, :66:24, :68:88, :69:{23,33}, :71:56]
      anonOut_a_bits_mask_rdata_1 <= auto_anon_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
    if (_anonOut_a_bits_mask_T_3 & anonOut_a_bits_mask_masked_enable_2)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:63:42, :66:24, :68:88, :69:{23,33}, :71:56]
      anonOut_a_bits_mask_rdata_2 <= auto_anon_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:66:24]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/OneHot.scala:65:12]
      repeat_sel_sel_sources_0 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h1)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_1 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h2)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_2 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h3)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_3 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h4)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_4 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h5)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_5 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h6)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_6 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h7)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_7 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h8)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_8 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h9)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_9 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'hA)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_10 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'hB)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_11 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'hC)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_12 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'hD)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_13 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'hE)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_14 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'hF)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_15 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (_repeat_sel_sel_T & auto_anon_in_a_bits_source == 5'h10)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :189:26, :193:39, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      repeat_sel_sel_sources_16 <= auto_anon_in_a_bits_address[4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:187:27, :188:38]
    if (repeat_first)	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:106:25]
      repeat_sel_hold_r <= _GEN_0;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:121:47]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
        end	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
        count = _RANDOM[4'h0][1:0];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :40:27]
        corrupt_reg = _RANDOM[4'h0][2];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :40:27, :45:32]
        anonOut_a_bits_data_rdata_written_once = _RANDOM[4'h0][3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :40:27, :62:41]
        anonOut_a_bits_data_rdata_0 = {_RANDOM[4'h0][31:4], _RANDOM[4'h1], _RANDOM[4'h2][3:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :40:27, :66:24]
        anonOut_a_bits_data_rdata_1 = {_RANDOM[4'h2][31:4], _RANDOM[4'h3], _RANDOM[4'h4][3:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24]
        anonOut_a_bits_data_rdata_2 = {_RANDOM[4'h4][31:4], _RANDOM[4'h5], _RANDOM[4'h6][3:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24]
        anonOut_a_bits_mask_rdata_written_once = _RANDOM[4'h6][4];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :62:41, :66:24]
        anonOut_a_bits_mask_rdata_0 = _RANDOM[4'h6][12:5];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24]
        anonOut_a_bits_mask_rdata_1 = _RANDOM[4'h6][20:13];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24]
        anonOut_a_bits_mask_rdata_2 = _RANDOM[4'h6][28:21];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24]
        repeat_count = _RANDOM[4'h6][30:29];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24, :105:26]
        repeat_sel_sel_sources_0 = {_RANDOM[4'h6][31], _RANDOM[4'h7][0]};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :66:24, :187:27]
        repeat_sel_sel_sources_1 = _RANDOM[4'h7][2:1];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_2 = _RANDOM[4'h7][4:3];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_3 = _RANDOM[4'h7][6:5];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_4 = _RANDOM[4'h7][8:7];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_5 = _RANDOM[4'h7][10:9];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_6 = _RANDOM[4'h7][12:11];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_7 = _RANDOM[4'h7][14:13];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_8 = _RANDOM[4'h7][16:15];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_9 = _RANDOM[4'h7][18:17];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_10 = _RANDOM[4'h7][20:19];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_11 = _RANDOM[4'h7][22:21];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_12 = _RANDOM[4'h7][24:23];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_13 = _RANDOM[4'h7][26:25];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_14 = _RANDOM[4'h7][28:27];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_15 = _RANDOM[4'h7][30:29];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_sel_sources_16 = {_RANDOM[4'h7][31], _RANDOM[4'h8][0]};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :187:27]
        repeat_sel_hold_r = _RANDOM[4'h8][2:1];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :121:47, :187:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_6 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (anonIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:76:29]
    .io_in_a_valid        (auto_anon_in_a_valid),
    .io_in_a_bits_opcode  (auto_anon_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_anon_in_a_bits_param),
    .io_in_a_bits_size    (auto_anon_in_a_bits_size),
    .io_in_a_bits_source  (auto_anon_in_a_bits_source),
    .io_in_a_bits_address (auto_anon_in_a_bits_address),
    .io_in_a_bits_mask    (auto_anon_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_anon_in_a_bits_corrupt),
    .io_in_d_ready        (auto_anon_in_d_ready),
    .io_in_d_valid        (_repeated_repeater_io_deq_valid),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_opcode  (_repeated_repeater_io_deq_bits_opcode),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_param   (_repeated_repeater_io_deq_bits_param),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_size    (_repeated_repeater_io_deq_bits_size),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_source  (_repeated_repeater_io_deq_bits_source),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_sink    (_repeated_repeater_io_deq_bits_sink),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_denied  (_repeated_repeater_io_deq_bits_denied),	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .io_in_d_bits_corrupt (_repeated_repeater_io_deq_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  Repeater_TLBundleD_a32d256s5k5z4u repeated_repeater (	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
    .clock               (clock),
    .reset               (reset),
    .io_repeat           (~repeat_last),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:107:35, :148:7]
    .io_enq_ready        (auto_anon_out_d_ready),
    .io_enq_valid        (auto_anon_out_d_valid),
    .io_enq_bits_opcode  (auto_anon_out_d_bits_opcode),
    .io_enq_bits_param   (auto_anon_out_d_bits_param),
    .io_enq_bits_size    (auto_anon_out_d_bits_size),
    .io_enq_bits_source  (auto_anon_out_d_bits_source),
    .io_enq_bits_sink    (auto_anon_out_d_bits_sink),
    .io_enq_bits_denied  (auto_anon_out_d_bits_denied),
    .io_enq_bits_data    (auto_anon_out_d_bits_data),
    .io_enq_bits_corrupt (auto_anon_out_d_bits_corrupt),
    .io_deq_ready        (auto_anon_in_d_ready),
    .io_deq_valid        (_repeated_repeater_io_deq_valid),
    .io_deq_bits_opcode  (_repeated_repeater_io_deq_bits_opcode),
    .io_deq_bits_param   (_repeated_repeater_io_deq_bits_param),
    .io_deq_bits_size    (_repeated_repeater_io_deq_bits_size),
    .io_deq_bits_source  (_repeated_repeater_io_deq_bits_source),
    .io_deq_bits_sink    (_repeated_repeater_io_deq_bits_sink),
    .io_deq_bits_denied  (_repeated_repeater_io_deq_bits_denied),
    .io_deq_bits_data    (_repeated_repeater_io_deq_bits_data),
    .io_deq_bits_corrupt (_repeated_repeater_io_deq_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_a_ready = anonIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :76:29]
  assign auto_anon_in_d_valid = _repeated_repeater_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_opcode = _repeated_repeater_io_deq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_param = _repeated_repeater_io_deq_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_size = _repeated_repeater_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_source = _repeated_repeater_io_deq_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_sink = _repeated_repeater_io_deq_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_denied = _repeated_repeater_io_deq_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_in_d_bits_data = _GEN_1[(repeat_first ? _GEN_0 : repeat_sel_hold_r) & _repeat_limit_T[4:3] | repeat_count];	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :105:26, :106:25, :121:{25,47}, :122:16, :126:24, :137:30, generators/rocket-chip/src/main/scala/util/package.scala:243:{71,76}]
  assign auto_anon_in_d_bits_corrupt = _repeated_repeater_io_deq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, generators/rocket-chip/src/main/scala/util/Repeater.scala:36:26]
  assign auto_anon_out_a_valid = auto_anon_in_a_valid & last;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :42:36, :77:29]
  assign auto_anon_out_a_bits_opcode = auto_anon_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  assign auto_anon_out_a_bits_param = auto_anon_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  assign auto_anon_out_a_bits_size = auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  assign auto_anon_out_a_bits_source = auto_anon_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  assign auto_anon_out_a_bits_address = auto_anon_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9]
  assign auto_anon_out_a_bits_mask =
    {anonOut_a_bits_mask_sub_15_1 | anonOut_a_bits_mask_sub_15_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_15_1 | anonOut_a_bits_mask_sub_15_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_14_1 | anonOut_a_bits_mask_sub_14_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_14_1 | anonOut_a_bits_mask_sub_14_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_13_1 | anonOut_a_bits_mask_sub_13_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_13_1 | anonOut_a_bits_mask_sub_13_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_12_1 | anonOut_a_bits_mask_sub_12_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_12_1 | anonOut_a_bits_mask_sub_12_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_11_1 | anonOut_a_bits_mask_sub_11_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_11_1 | anonOut_a_bits_mask_sub_11_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_10_1 | anonOut_a_bits_mask_sub_10_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_10_1 | anonOut_a_bits_mask_sub_10_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_9_1 | anonOut_a_bits_mask_sub_9_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_9_1 | anonOut_a_bits_mask_sub_9_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_8_1 | anonOut_a_bits_mask_sub_8_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_8_1 | anonOut_a_bits_mask_sub_8_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_7_1 | anonOut_a_bits_mask_sub_7_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_7_1 | anonOut_a_bits_mask_sub_7_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_6_1 | anonOut_a_bits_mask_sub_6_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_6_1 | anonOut_a_bits_mask_sub_6_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_5_1 | anonOut_a_bits_mask_sub_5_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_5_1 | anonOut_a_bits_mask_sub_5_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_4_1 | anonOut_a_bits_mask_sub_4_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_4_1 | anonOut_a_bits_mask_sub_4_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_3_1 | anonOut_a_bits_mask_sub_3_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_3_1 | anonOut_a_bits_mask_sub_3_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_2_1 | anonOut_a_bits_mask_sub_2_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_2_1 | anonOut_a_bits_mask_sub_2_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_1_1 | anonOut_a_bits_mask_sub_1_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_1_1 | anonOut_a_bits_mask_sub_1_2 & ~(auto_anon_in_a_bits_address[0]),
     anonOut_a_bits_mask_sub_0_1 | anonOut_a_bits_mask_sub_0_2 & auto_anon_in_a_bits_address[0],
     anonOut_a_bits_mask_sub_0_1 | anonOut_a_bits_mask_sub_0_2 & ~(auto_anon_in_a_bits_address[0])} & (auto_anon_in_a_bits_opcode[2] ? 32'hFFFFFFFF : {auto_anon_in_a_bits_mask, anonOut_a_bits_mask_masked_enable_2 ? auto_anon_in_a_bits_mask : anonOut_a_bits_mask_rdata_2, anonOut_a_bits_mask_masked_enable_1 ? auto_anon_in_a_bits_mask : anonOut_a_bits_mask_rdata_1, anonOut_a_bits_mask_masked_enable_0 ? auto_anon_in_a_bits_mask : anonOut_a_bits_mask_rdata_0});	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :63:42, :66:24, :68:88, :73:12, :85:{88,93}, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
  assign auto_anon_out_a_bits_data = {auto_anon_in_a_bits_data, anonOut_a_bits_data_masked_enable_2 ? auto_anon_in_a_bits_data : anonOut_a_bits_data_rdata_2, anonOut_a_bits_data_masked_enable_1 ? auto_anon_in_a_bits_data : anonOut_a_bits_data_rdata_1, anonOut_a_bits_data_masked_enable_0 ? auto_anon_in_a_bits_data : anonOut_a_bits_data_rdata_0};	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :63:42, :66:24, :68:88, :73:12]
  assign auto_anon_out_a_bits_corrupt = corrupt_out;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:27:9, :47:36]
endmodule

